### ISSUE TITLE
Rendering on mobile skewed to the left on Chrome (76.0.3809)

### ISSUE THREAD

**Issue by fiatexodus** [htmlstreamofficial/awesome-dashboard-ui-kit#1]
From my HN comment (not sure if you folks are too concerned w/ mobile and phones this old given the use case for this kit):  

One thing I saw was during my mobile litmus test (Chrome developer tools set to iPhone 5SE), it didn't render using the full screen width, being offset left. Checking the element dimensions confused me because they matched those given for the device. Perhaps an issue in Chrome I'm using (76.0.3809)--when I inspect I see that the root element width of 320x568 matches that stated for the device. Looks fine on other device emulations with more than 400 pixels of width.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/16608312/63320186-202d2780-c2da-11e9-9615-e192548c1053.png">

**Comment by jahaganiev** [comment]
Hi, thank you for the report. You can control the display components with utility classes. For example, you can use d-none d-sm-inline-block classes and hide some blocks on the 320px screen.

**Comment by ruslan-garaev** [comment]
Hi, @AC-FTW!
@jahaganiev is right – for example, you can hide logo block on the 320px screen:
```
      <!-- Header Left Section -->
      <div class="u-header-left d-none d-sm-flex">
        <!-- Header Logo -->
        <a class="u-header-logo" href="index.html">
          <img class="u-header-logo__icon" src="assets/svg/logo-mini.svg" alt="Awesome Icon">
          <img class="u-header-logo__text" src="assets/svg/logo-text-light.svg" alt="Awesome">
        </a>
        <!-- End Header Logo -->
      </div>
      <!-- End Header Left Section -->
```
And don't forget to correct legends on "Performance Chart" Card.

Example – https://htmlstream.com/preview/awesome-dashboard-ui-kit/test/index-20.08.19.html

Thanks a lot for sharing your feedback!
